const jwt = require('jsonwebtoken');
const { features } = require('../utils/features');
const { default: Redis } = require('ioredis');
const { parseCookies } = require('./oauth/sessionCheck');
require('dotenv').config();
const redisTokenConnect = new Redis({
  host: process.env.HOST,
  port: process.env.RD_PORT,
  username: process.env.RD_USERNAME,
  password: process.env.redisPass
});
const verifyTokenSocket = (token, callback) => {
  if (!token) {
    return callback('Token is required');
  }

  const options = { algorithms: ['HS512'] }; // Specify the HS512 algorithm

  jwt.verify(token, process.env.JWT_SECRET_KEY, options, (err, decoded) => {
    if (err) {
      return callback('Invalid token');
    } 
    // Optionally attach decoded information to the socket
    callback(null, decoded);
  });
};
const requestToken = (req) => {
  const authHeader = String(req.headers?.authorization || '');
  const match = authHeader.match(/^Bearer\s+(.+)$/i);
  const bearer = match?.[1]?.trim();
  if (bearer && bearer !== 'null' && bearer !== 'undefined') return bearer;

  const cookies = parseCookies(req.headers?.cookie);
  return cookies['adsgpt-session'] || cookies['access-token'] || '';
};
const authenticateJWT = (req, res, next) => {
  const token = requestToken(req);
  const options = { algorithms: ['HS512'] };
  if (token) {
    jwt.verify(token, process.env.JWT_SECRET_KEY, options, (err, user) => {
      if (err) {
        return res.sendStatus(403);
      }
      if(user?.created_from=="PAS") user.user_id = `PAS-${user.user_id}`
      if(user?.created_from=="GPT") user.user_id = `GPT-${user.user_id}`
      req.user = user;
      next();
    });
  } 
  else {
    res.sendStatus(401);
  }
};
const verifySecretKey = (req, res, next) => {
  const providedKey = req.headers["x-secret-key"];

  if (!providedKey || providedKey !== process.env.RESULT_UPDATE_SECRET) {
    return res.status(401).json({
      success: false,
      message: "Unauthorized: Invalid or missing secret key",
    });
  }

  next();
};

const generateJWT = (user) => {
  const payload = {
    id: user.id,
    username: user.username,
    // Add any other user details you want to include in the token
  };

  const options = {
    algorithm: 'HS512',
    expiresIn: '1h', // Token expiration time
  };

  const token = jwt.sign(payload, process.env.JWT_SECRET_KEY, options);
  return token;
};
const generateToken = (payload, secretKey, expiryTime, autoGenerated=false) => {
  payload.autoGenerated= autoGenerated
  return jwt.sign(payload, secretKey, { algorithm: 'HS512', expiresIn: `${expiryTime}m` });
};


const TokenDecode = (token) => {
  if (!token) {
    throw new Error("Token required");
  }
  
  const options = { algorithms: ['HS512'] }; // Specify the HS512 algorithm

  try {
    // Use the synchronous version of jwt.verify
    const decoded = jwt.verify(token, process.env.JWT_SECRET_KEY, options);
    if (decoded.created_from === 'PAS') {
      // Extract the current date from the userSubscriptionType object
      const currentSubscriptionDate = Object.values(decoded.userSubscriptionType)[0];
      
      // Update the userSubscriptionType to have 'PAS' as the key and the same date
      decoded.userSubscriptionType = { 'PAS': currentSubscriptionDate };
    }   
     return decoded;
  } catch (err) {
    throw new Error("Invalid or expired token");
  }
};
const deleteKeysFromObject = (input, keysToDelete)=> {
  try {
      // Check if keysToDelete is a valid array
      if (!Array.isArray(keysToDelete)) {
          throw new Error("Invalid input: keysToDelete must be an array.");
      }

      // Function to delete keys from a single object
      const deleteFromObject = (obj) => {
          for (let key in obj) {
              if (obj.hasOwnProperty(key)) {
                  // If the key matches any in keysToDelete, delete it
                  if (keysToDelete.includes(key)) {
                      delete obj[key];
                  }
                  // If the value is a nested object or array, recurse into it
                  else if (typeof obj[key] === 'object' && obj[key] !== null) {
                      deleteKeysFromObject(obj[key], keysToDelete);
                  }
              }
          }
          return obj; // Return the modified object
      };

      // Check if the input is an array
      if (Array.isArray(input)) {
          return input.map(item => {
              if (typeof item === 'object' && item !== null) {
                  return deleteFromObject(item);
              }
              return item; // Return non-object elements as is
          });
      } else if (typeof input === 'object' && input !== null) {
          // If it's a single object, apply deletion and return the object
          return deleteFromObject(input);
      } else {
          throw new Error("Invalid input: The provided input is neither an object nor an array of objects.");
      }
  } catch (error) {
      console.error(error.message);
      return null; // Return null in case of an error
  }
}

function restrictChartBottomeBasedOnSubscription(response, features, subscriptionType) {
  const modifiedResponse = { ...response };

  // Extract plan permissions for each feature
  const chartPlans = features["Distribution of Call to Action"].plans;
  const geoPlans = features["Geographical Distribution of Ads"].plans;
  const engagementPlans = features["Engagement Comparison Across Ad Formats"].plans;
  const advertiserSearch = features["Advertiser Search"].plans[subscriptionType];
  const distributionOfCallToAction = chartPlans[subscriptionType];
  const geographicalDistribution = geoPlans[subscriptionType];
  const engagementComparison = engagementPlans[subscriptionType];

  // Add "Ad Count by Post Owner" plan permissions
  const adCountPlans = features["Ad Count by Post Owner"].plans;
  const adCountByPostOwner = adCountPlans[subscriptionType];

  // Modify the "analyticsChart" based on the allowed features for the subscription type
  modifiedResponse.analyticsChart = response.analyticsChart.filter(chart => {
    if (chart.title === "Distribution of Call to Actions") {
      return distributionOfCallToAction;
    }
    if (chart.title === "Geographical Distribution of Ads") {
      return geographicalDistribution;
    }
    if (chart.title === "Engagement Comparison Across Ad Formats") {
      return engagementComparison;
    }
    if (chart.title === "Ad Count by Post Owner") {  // Handle Ad Count by Post Owner
      return adCountByPostOwner;
    }
    return true; // Keep other charts
  });

  // Update advertiser search access
  modifiedResponse.advertiserSearchEnabled = advertiserSearch;

  return modifiedResponse;
}

const authenticateJWTInteraction = (req, res, next) => {
  try {
    const token = requestToken(req);
    const options = { algorithms: ['HS512'] };

    if (token) {
      return jwt.verify(token, process.env.JWT_SECRET_KEY, options, (err, user) => {
        if (err) return res.sendStatus(403);

        if (user?.created_from === "PAS") user.user_id = `PAS-${user.user_id}`;
        if (user?.created_from === "GPT") user.user_id = `GPT-${user.user_id}`;

        req.user = user;
        return next(); 
      });
    }

    if (req?.session?.token) {
      return jwt.verify(req.session.token, process.env.JWT_SECRET_KEY, options, (err, user) => {
        if (err) return res.sendStatus(403);

        req.user = user;
        return next(); 
      });
    }

    return res.sendStatus(401); 

  } catch (error) {
    
  }
};

module.exports = {
  verifyTokenSocket,
  authenticateJWT,
  verifySecretKey,
  generateJWT, 
  generateToken,
  TokenDecode, 
  deleteKeysFromObject,
  restrictChartBottomeBasedOnSubscription,
  authenticateJWTInteraction
};
