const express = require("express");
const draftRouter = require("./darftRoute");
const adCopyRouter = require("./adsCopyChat");
const adCretiveRouter = require("./adCreative");
const adVideoRouter = require("./adVideo");
const adCopyDraftRouter = require("./adCopyDraft");
const adCreativeDraftRouter = require("./adCreativeDraft");
const chatRouter = require("./chatRoute");
const getScrollAdsRouter = require("./getScrollads");
const faqRouter = require("./faqRoutes");
const {
  authenticateJWT,
  authenticateJWTInteraction,
} = require("../services/authService");
const loginRoute = require("./loginRoutes");
const profileRoutes = require("./profileRoutes");
const trendingRoute = require("./trendingTopics");
const ipLocationRoter = require("./ipLocationRoute");
const tracksRoutes = require("./tracks/accesslogs");
const checkAuth = require("./auth/userCheckRoute");
const advertiserSearch = require("./advertiserSearch");
const amemberRoute = require("./auth/amemberRoute");
const userInteractionData = require("./userInteractionRoute");
const chatPageRoutes = require("./chatPageRouter");
const adminLogin = require("./adminLogin");
const downloadImgUrl = require("./downloadImgUrl");
const brandName = require("./brandName");
const initCount = require("./chatCounterRoutes");
const canvaRoutes = require("./canvaRoutesV2");
const analyticsRoutes = require("./analyticsRoutes");
const newHistoryRoutes = require("./newHistory");
const videoRenderRoutes = require("./videoRenderRoutes");
const queryRouter = require("./queryRoutes");
const galleryRoutes = require("../Router/gallery");
const userCreditData = require("../Router/creditRoutes");
const campaignRoutes = require("./adFactory");
const adPostingRoutes = require("./adPostingRoutes");
const getCategoryRoutes = require("../Router/adFactoryCategory");
const Usage = require("../Router/usage.route");
const metaAdRoutes = require("./adPosting/metaAdRoutes");
const googleAdRoutes = require("./adPosting/googleAdRoutes");
const tiktokAdRoutes = require("./adPosting/tiktokAdRoutes");
const videoGenerationRoutes = require("./videoRoutes");
const imageGenerationRoutes = require("./imageRoutes");
const avatarRoutes = require("./avatarRoutes");
const generatedMediaRoutes = require("./generatedMedia.route");
const adStudioRoutes = require("./adStudio");
const adminApiRoutes = require("./adminApi.route");
const newsletterTestRoutes = require("./newsletterTestRoutes");
const adsFactoryAutoPilotRoutes = require("./adsFactoryAuto/adsFactoryAutoPilotRoutes");
const voiceSelectorRoutes = require("./voiceSelectorRoutes");
const promptTemplateRoutes = require("./promptTemplate/promptTemplateRoutes");
const creditsApiRoutes = require("./creditsApiRoutes");
const landingPageAnalyzerRoutes = require("./landingPageAnalyzer/landingPageAnalyzerRoutes");
const deviceTokenRoutes = require("./deviceTokenRoutes");
const partnerMetaAdsRoutes = require("./partnerApi/metaAdsRoutes");
const workspaceRoutes = require("./workspaceRoutes");
const workspaceMemberAuthRoutes = require("./workspaceMemberAuthRoutes");
const amemberSsoRoute = require("./auth/amemberSsoRoute");
const mobileRoutes = require("./auth/mobileRoutes");

const app = express();
app.use("/mobile", mobileRoutes);
app.use("/adcopy", authenticateJWT, adCopyRouter);
app.use("/adCreative", authenticateJWT, adCretiveRouter);
app.use("/adVideo", authenticateJWT, adVideoRouter);
app.use("/chat", authenticateJWT, chatRouter);
//app.use('/adsscroll', authenticateJWT, getScrollAdsRouter );
app.use("/draft", authenticateJWT, draftRouter);
app.use("/AdCopydraft", authenticateJWT, adCopyDraftRouter);
app.use("/AdCreativedraft", authenticateJWT, adCreativeDraftRouter);
app.use("/faq", authenticateJWT, faqRouter);
app.use("/ip-location", ipLocationRoter);
//app.use("/login", loginRoute);
//app.use("/profile", profileRoutes);
app.use("/trending", authenticateJWT, trendingRoute);
app.use("/chat-settings", authenticateJWT, chatPageRoutes);
app.use("/track", tracksRoutes);
app.use("/check-access", checkAuth);
app.use("/workspace-auth", workspaceMemberAuthRoutes);
app.use("/auth/amember", amemberSsoRoute);
app.use("/advertiser-search", advertiserSearch);
app.use("/amember", amemberRoute);
app.use(
  "/user-intreaction-data",
  authenticateJWTInteraction,
  userInteractionData,
);
app.use("/user-credit-data", userCreditData);
app.use("/admin-panel", adminLogin);
app.use("/img", downloadImgUrl);
app.use("/brand", authenticateJWT, brandName);
app.use("/prompt", initCount);
app.use("/backup", queryRouter);
app.use("/canva", canvaRoutes);
app.use("/analytics", analyticsRoutes);
app.use("/history", authenticateJWT, newHistoryRoutes);
app.use("/video-render", videoRenderRoutes);
app.use("/gallery", authenticateJWT, galleryRoutes);
app.use("/campaign", campaignRoutes);
app.use("/ad-posting", authenticateJWT, adPostingRoutes);
app.use("/getCategory", getCategoryRoutes);
app.use("/usage", Usage);
app.use("/meta-ads", authenticateJWT, metaAdRoutes);
app.use("/workspaces", authenticateJWT, workspaceRoutes);
// Partner-facing surface: no AdsGPT JWT — auth is the partner's own Meta
// System User token, validated inside partnerMetaAdsRoutes itself.
app.use("/partner-api/v1/meta-ads", partnerMetaAdsRoutes);
app.use("/google-ads", authenticateJWT, googleAdRoutes);
app.use("/tiktok-ads", authenticateJWT, tiktokAdRoutes);
app.use("/video", videoGenerationRoutes);
app.use("/image", imageGenerationRoutes);
app.use("/avatar", authenticateJWT, avatarRoutes);
app.use("/generated-media", generatedMediaRoutes);
app.use("/ad-studio", adStudioRoutes);
app.use("/admin", adminApiRoutes);
app.use("/newsletter-test", newsletterTestRoutes);
app.use("/voice-selector", authenticateJWT, voiceSelectorRoutes);
app.use("/ads-factory/autopilot", adsFactoryAutoPilotRoutes);
app.use("/prompt-templates", promptTemplateRoutes);
app.use("/credits", creditsApiRoutes);
app.use("/landing-page-analyzer", landingPageAnalyzerRoutes);
app.use("/device-tokens", authenticateJWT, deviceTokenRoutes);

module.exports = app;
