import React, { useEffect } from 'react';
import {
  Bot,
  ChartNoAxesColumn,
  ChevronLeft,
  History,
  Library,
  LogOut,
  ScanSearch,
  Sparkles,
  Users,
  Zap,
} from 'lucide-react';
import AdsGPTLogoDarkLogo from '@/assets/layouts/adsgpt-dark-mode-logo.svg';
import AdsGPTLogo from '@/assets/layouts/adsgpt-logo.webp';
import AdsGPTLightModeLogo from '@/assets/layouts/adsgpt-light-mode-logo.png';
import brandIQDarkLogo from '@/assets/layouts/appsidebar/brand-iq-dark.svg';
import adStudioDarkLogo from '@/assets/layouts/appsidebar/ad-studio-dark.svg';
import adFactoryDarkLogo from '@/assets/layouts/appsidebar/ad-factory-dark.svg';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import ChatHistorySection from '@/components/common/AdPrompt/ChatHistorySection';
import { Sidebar, useSidebar } from '@/components/ui/sidebar';
import { ShadcnTooltip } from '../ShadcnTooltip';
import { initNewChat } from '@/store/actions/adStudio/adCreativeActions';
import { resetAdFactorNewSlice } from '@/store/reducers/adFactoryNew/adFactoryNewSlice';
import { setActiveBrandIQTab } from '@/store/reducers/brandIQ/brandIQTabsSlice';
import { fetchProcessingCount } from '@/store/actions/adVideoNew/Advideoactions';
import { setActivePage } from '@/store/reducers/adStudio/adVideoNewSlice';
import {
  setActiveAdStudioTab,
  setAdCreativeNewActivePage,
} from '@/store/reducers/adStudio/adStudioTabsSlice';
import { IS_AI_ASSISTANT_ENABLED, IS_LANDING_ANALYZER_ENABLED } from '@/utils/featureFlags';
import {
  canUseWorkspaceFeature,
  canUseMySpace,
  clearWorkspaceToken,
  isWorkspaceMember,
  sessionPayload,
} from '@/utils/workspaceSession';

// ── Static navigation group definitions ────────────────────────────────────
// Items defined here; permission filtering happens inside the component.
const NAV_GROUPS_STATIC = [
  {
    id: 'create',
    label: 'CREATE',
    items: [
      {
        id: 'adfactory',
        label: 'Ad Factory',
        compactLabel: 'AdFactory',
        link: '/adfactory',
        icon: adFactoryDarkLogo,
        featureKey: 'adFactory',
      },
      IS_AI_ASSISTANT_ENABLED && {
        id: 'ai',
        label: 'AI Assistant',
        compactLabel: 'AI',
        link: '/assistant',
        lucideIcon: Bot,
        featureKey: 'assistant',
      },
      {
        id: 'adstudio',
        label: 'Ad Studio',
        compactLabel: 'AdStudio',
        link: '/adstudio',
        icon: adStudioDarkLogo,
        lightIcon: Sparkles,
        featureKey: 'adStudio',
      },
      IS_LANDING_ANALYZER_ENABLED && {
        id: 'landing-analyzer',
        label: 'Analyzer',
        compactLabel: 'Analyzer',
        link: '/landing-page-analyzer',
        lucideIcon: ScanSearch,
        badge: 'NEW',
        featureKey: 'analyzer',
      },
    ].filter(Boolean),
  },
  {
    id: 'measure',
    label: 'MEASURE',
    items: [
      {
        id: 'brandiq',
        label: 'BrandIQ',
        compactLabel: 'BrandIQ',
        link: '/brandiq',
        icon: brandIQDarkLogo,
        lightIcon: Zap,
        featureKey: 'brandIq',
      },
      {
        id: 'meta-ads',
        label: 'Ads Manager',
        compactLabel: 'Ads Manager',
        link: '/ads-manager',
        lucideIcon: ChartNoAxesColumn,
        badge: 'BETA',
        featureKey: 'adsManager',
      },
    ],
  },
];

const AppSidebar = () => {
  const {
    isMobile,
    openMobile,
    setOpenMobile,
    setOpenHistory,
    openHistory,
    isNavExpanded,
    toggleNavExpanded,
  } = useSidebar();

  const location = useLocation();
  const currentRoute = location.pathname;
  const dispatch = useDispatch();
  const { userData } = useSelector((state) => state.socket);

  const workspacePayload = sessionPayload();
  const memberSession = isWorkspaceMember(workspacePayload);

  // ── Profile info ────────────────────────────────────────────────────────
  const profileDisplayName = memberSession
    ? workspacePayload.actorUserName || workspacePayload.actorUserEmail || 'Workspace member'
    : userData?.user_name || 'User';
  const profileFooterLabel = memberSession ? 'Workspace account' : 'Account';
  const profileImage = memberSession ? '' : userData?.profileImage;

  const profileInitials = (() => {
    if (memberSession) return profileDisplayName.slice(0, 2).toUpperCase();
    const firstName = userData?.name_f || '';
    const lastName = userData?.name_l || '';
    const userName = userData?.user_name || 'U';
    const login = userData?.login || 'AG';
    if (userData?.autoGenerated) return login?.slice(0, 2).toUpperCase();
    if (firstName && lastName) return `${firstName[0]}${lastName[0]}`.toUpperCase();
    if (firstName) return firstName.slice(0, 2).toUpperCase();
    if (lastName) return lastName.slice(0, 2).toUpperCase();
    return userName.slice(0, 2).toUpperCase();
  })();

  // Workspace subtitle shown in expanded header
  const workspaceSubtitle = memberSession
    ? workspacePayload.workspaceName || 'Workspace'
    : userData?.company_name || userData?.login || 'Personal';

  const activeAdStudioTabId = useSelector((state) => state.adStudioTabs.activeAdStudioTabId);
  const { activePage, savedCount } = useSelector((state) => state.adVideoNew);

  // Poll for processing count
  useEffect(() => {
    const fetchCount = () => dispatch(fetchProcessingCount());
    fetchCount();
    const interval = setInterval(fetchCount, 15000);
    return () => clearInterval(interval);
  }, [dispatch]);

  // ── Close history when leaving adCopy tab ─────────────────────────────
  useEffect(() => {
    if (!(currentRoute === '/adstudio' && activeAdStudioTabId === 'adCopy')) {
      setOpenHistory(false);
    }
  }, [activeAdStudioTabId, currentRoute, setOpenHistory]);

  // ── Active route detection ──────────────────────────────────────────────
  const isItemActive = (item) => {
    if (item.id === 'meta-ads') {
      return (
        currentRoute === '/ads-manager' ||
        currentRoute.startsWith('/meta-ads') ||
        currentRoute.startsWith('/google-ads') ||
        currentRoute.startsWith('/tiktok-ads') ||
        currentRoute.startsWith('/autopilot')
      );
    }
    if (item.id === 'adstudio') {
      // Don't mark adstudio active on myVideos my-space page
      const isMySpace =
        currentRoute === '/adstudio' &&
        activeAdStudioTabId === 'adVideoNew' &&
        activePage === 'myVideos';
      return (
        !isMySpace &&
        (currentRoute === item.link || (item.link !== '/' && currentRoute.startsWith(item.link)))
      );
    }
    return currentRoute === item.link || (item.link !== '/' && currentRoute.startsWith(item.link));
  };

  // ── Nav click side-effects (dispatch + mobile close) ───────────────────
  const handleNavClick = (link) => {
    if (link === '/adstudio') dispatch(initNewChat());
    else if (link === '/adfactory' && currentRoute !== '/adfactory')
      dispatch(resetAdFactorNewSlice());
    else if (link === '/brandiq') dispatch(setActiveBrandIQTab('myBrands'));
    if (isMobile) setOpenMobile(false);
  };

  // ── Logo click: navigate to Ad Studio Ad Creative ───────────────────────
  const handleLogoClick = () => {
    dispatch(setActiveAdStudioTab('adCreativeNew'));
    dispatch(setAdCreativeNewActivePage('home'));
    setOpenHistory(false);
    if (isMobile) setOpenMobile(false);
  };

  // ── Permission-filtered navigation groups ──────────────────────────────
  const visibleNavGroups = NAV_GROUPS_STATIC.map((group) => ({
    ...group,
    items: group.items.filter((item) =>
      canUseWorkspaceFeature(item.featureKey, workspacePayload)
    ),
  })).filter((g) => g.items.length > 0);

  // ── LIBRARY group items (permission gated) ─────────────────────────────
  const showWorkspace = !memberSession;
  const showMySpace = canUseMySpace(workspacePayload);
  const showLibraryGroup = showWorkspace || showMySpace;

  // ── Layout mode: showExpanded = wide nav with labels ───────────────────
  // Sidebar expansion is permanently disabled; the sidebar remains in compact mode.
  const showExpanded = false;

  // ── Badge renderer ─────────────────────────────────────────────────────
  const renderBadge = (badge) => {
    if (!badge) return null;
    const isNumeric = typeof badge === 'number';
    return (
      <span
        className={`sidebar-badge inline-flex flex-shrink-0 items-center justify-center font-bold leading-none ${
          isNumeric
            ? showExpanded
              ? 'sidebar-badge--numeric h-[20px] min-w-[20px] rounded-full px-1.5 text-[9px] text-white dark:w-[18px] dark:px-0 dark:text-[9px] dark:bg-[#5E66F5]'
              : 'sidebar-badge--numeric h-[18px] w-[18px] rounded-full text-[7px] 2xl:text-[9px] text-white dark:bg-[#5E66F5]'
            : showExpanded
              ? 'sidebar-badge--label rounded-full px-[8px] py-[2.5px] text-[8px] uppercase tracking-[0.06em] dark:rounded-[4px] dark:bg-[#2A2A2A] dark:px-[5px] dark:py-[2px] dark:text-[8.5px] dark:tracking-wide dark:text-[#AFAFAF]'
              : 'sidebar-badge--label rounded-[4px] px-[5px] py-[2px] text-[6px] 2xl:text-[8.5px] uppercase tracking-wide dark:bg-[#2A2A2A] dark:text-[#AFAFAF]'
        }`}
      >
        {badge}
      </span>
    );
  };

  // ── Icon renderer ──────────────────────────────────────────────────────
  const renderIcon = (item, expanded) => {
    const cls = expanded ? 'h-[26px] w-[26px] flex-shrink-0' : 'h-[24px] w-[24px] flex-shrink-0';
    const LightIcon = item.lightIcon;

    // Ad Studio keeps its Sparkles mark in both themes for a consistent identity.
    if (item.id === 'adstudio' && LightIcon) {
      return <LightIcon className={`${cls} sidebar-nav-icon`} aria-hidden="true" />;
    }

    if (LightIcon && item.icon) {
      return (
        <>
          <LightIcon className={`${cls} sidebar-nav-icon dark:hidden`} aria-hidden="true" />
          <img
            src={item.icon}
            className={`${cls} sidebar-nav-icon hidden object-contain dark:block dark:invert dark:opacity-70`}
            alt=""
            aria-hidden="true"
          />
        </>
      );
    }

    if (item.lucideIcon) {
      return <item.lucideIcon className={`${cls} sidebar-nav-icon`} aria-hidden="true" />;
    }
    return (
      <img
        src={item.icon}
        className={`${cls} sidebar-nav-icon${item.id === 'adfactory' ? ' sidebar-adfactory-icon' : ''} object-contain brightness-0 dark:invert dark:opacity-70`}
        alt=""
        aria-hidden="true"
      />
    );
  };

  // ── Single nav item (collapsed column layout) ──────────────────────────
  const CollapsedNavItem = ({ item, isActive, onClick }) => (
    <ShadcnTooltip label={item.label} side="right">
      <NavLink
        to={item.link}
        onClick={onClick}
        aria-label={item.label}
        aria-current={isActive ? 'page' : undefined}
        className={`sidebar-nav-item sidebar-nav-item--compact${isActive ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full flex-col items-center justify-center gap-1.5 rounded-[14px] py-2 ${
          item.badge ? 'h-[90px]' : 'h-[76px]'
        }`}
      >
        {isActive && (
          <span
            aria-hidden="true"
            className="nav-accent-bar absolute -left-2 top-3.5 bottom-3.5 w-[3px] rounded-r-full dark:left-0 dark:top-2 dark:bottom-2"
          />
        )}
        <div className="flex h-7 w-7 items-center justify-center">
          {renderIcon(item, false)}
        </div>
        <span className="sidebar-nav-label sidebar-nav-label--compact whitespace-nowrap dark:text-[#AFAFAF]">
          {item.compactLabel || item.label}
        </span>
        {item.badge && (
          <div className="sidebar-nav-badge--compact absolute right-0 2xl:right-2 -top-2">
            {renderBadge(item.badge)}
          </div>
        )}
      </NavLink>
    </ShadcnTooltip>
  );

  // ── Single nav item (expanded row layout) ─────────────────────────────
  const ExpandedNavItem = ({ item, isActive, onClick }) => (
    <NavLink
      to={item.link}
      onClick={onClick}
      aria-current={isActive ? 'page' : undefined}
      className={`sidebar-nav-item sidebar-nav-item--expanded${isActive ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5`}
    >
      {isActive && (
        <span
          aria-hidden="true"
          className="nav-accent-bar absolute left-0 top-[12px] bottom-[12px] w-[2.5px] rounded-r-full"
        />
      )}
      <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
        {renderIcon(item, true)}
      </div>
      <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1">{item.label}</span>
      {item.badge && renderBadge(item.badge)}
    </NavLink>
  );

  // ── Section group header ────────────────────────────────────────────────────────────
  const SectionHeader = ({ label, first = false }) => (
    <div
      className={`${
        showExpanded
          ? `px-4.5 pb-2 ${first ? 'pt-3.5' : 'pt-5.5'}`
          : `flex flex-col items-center justify-center px-1 pb-2 2xl:pb-3 ${
              first ? 'pt-3.5 2xl:pt-4.5' : 'pt-3 2xl:pt-3.5'
            }`
      }`}
    >
      {!showExpanded && !first && (
        <div className="sidebar-section-divider mb-3 2xl:mb-3.5 h-px w-9 dark:bg-white/15" />
      )}
      <span className="sidebar-section-label uppercase dark:leading-normal dark:text-[#999]">
        {label}
      </span>
    </div>
  );

  // ── Logo box (dark rounded square with icon) ───────────────────────────
  const SidebarLogoMark = ({ className = '' }) => (
    <img
      src={AdsGPTLogoDarkLogo}
      className={`${className} object-contain`}
      alt=""
      aria-hidden="true"
    />
  );

  const LogoIconBox = ({ size = 'md' }) => {
    const cls =
      size === 'md'
        ? 'sidebar-logo-shell sidebar-logo-shell--light-mark flex h-[38px] w-[38px] flex-shrink-0 items-center justify-center rounded-[11px] dark:h-8 dark:w-8 dark:rounded-[9px] dark:bg-[#2A2A2A]'
        : 'sidebar-logo-shell sidebar-logo-shell--light-mark flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-[9px] dark:bg-[#2A2A2A]';
    return (
      <div className={cls}>
        <SidebarLogoMark className="h-[30px] w-[30px] dark:h-[22px] dark:w-[22px]" />
      </div>
    );
  };

  return (
    <Sidebar
      collapsible="icon"
      className={
        currentRoute === '/assistant' ? '[&_[data-slot=sidebar-inner]]:bg-transparent' : undefined
      }
    >
      <div className="lm-sidebar-surface relative flex h-full w-full flex-col bg-sidebar dark:bg-[#0F0F0F]">

        {/* ── BRAND HEADER ────────────────────────────────────────────────── */}
        <div className="flex-shrink-0">
          {openHistory ? (
            /* History open — full brand logo covering the space + close history button */
            <div className="flex h-[60px] 2xl:h-[68px] items-center justify-between gap-3 pl-5 pr-3.5">
              <Link
                to="/adstudio"
                onClick={handleLogoClick}
                aria-label="Home - Ad Studio Ad Creative"
                className="flex min-w-0 flex-1 items-center cursor-pointer transition-transform hover:scale-[1.02] active:scale-[0.98] focus:outline-none"
              >
                {/* Light mode full logo */}
                <img
                  src={AdsGPTLightModeLogo}
                  alt="AdsGPT"
                  className="h-8 2xl:h-9 w-auto max-w-[150px] 2xl:max-w-[165px] object-contain object-left dark:hidden"
                />
                {/* Dark mode full logo */}
                <img
                  src={AdsGPTLogo}
                  alt="AdsGPT"
                  className="hidden h-8 2xl:h-9 w-auto max-w-[150px] 2xl:max-w-[165px] object-contain object-left dark:block"
                />
              </Link>
              <ShadcnTooltip label="Close history">
                <button
                  type="button"
                  onClick={() => setOpenHistory(false)}
                  aria-label="Close history"
                  className="sidebar-header-control flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full text-neutral-500 hover:text-neutral-900 transition-all hover:bg-black/5 dark:text-[#888888] dark:hover:text-white dark:hover:bg-white/10"
                >
                  <ChevronLeft className="h-4 w-4" aria-hidden="true" />
                </button>
              </ShadcnTooltip>
            </div>
          ) : (
            /* Collapsed — logo icon mark navigation to Ad Studio Ad Creative (Home button) */
            <div className="relative flex h-[60px] 2xl:h-[74px] items-center justify-center">
              <Link
                to="/adstudio"
                onClick={handleLogoClick}
                aria-label="Home - Ad Studio Ad Creative"
                className="group relative flex h-12 w-12 items-center justify-center rounded-xl transition-transform hover:scale-105 active:scale-95 focus:outline-none cursor-pointer"
              >
                <SidebarLogoMark className="sidebar-compact-logo-mark w-10 h-10 2xl:h-12 2xl:w-12 object-contain" />
              </Link>
            </div>
          )}
        </div>

        {/* ── DIVIDER ────────────────────────────────────────────────────────── */}
        <div
          className={
            openHistory
              ? 'sidebar-divider mx-4 flex-shrink-0 border-t border-black/10 dark:border-white/15'
              : 'sidebar-section-divider mx-auto h-px w-9 flex-shrink-0 dark:bg-white/15'
          }
        />

        {/* ── CHAT HISTORY SECTION (only when open) ─────────────────────────── */}
        {openHistory && activeAdStudioTabId === 'adCopy' && (
          <div className="flex min-h-0 flex-1 flex-col overflow-y-auto">
            <ChatHistorySection isSidebarOpen={openHistory} />
          </div>
        )}

        {/* ── NAVIGATION ────────────────────────────────────────────────────── */}
        {!openHistory && (
          <nav
            id="app-sidebar-navigation"
            aria-label="Primary navigation"
            className={`flex min-h-0 flex-1 flex-col overflow-y-auto scrollbar-hide pb-2`}
          >

            {/* Main nav groups: CREATE, MEASURE */}
            {visibleNavGroups.map((group, index) => (
              <div key={group.id}>
                <SectionHeader label={group.label} first={index === 0} />
                <div className={showExpanded ? 'space-y-1 px-2.5' : 'space-y-1 2xl:space-y-2 px-2'}>
                  {group.items.map((item) => {
                    const active = isItemActive(item);
                    const onClick = () => handleNavClick(item.link);
                    return showExpanded ? (
                      <ExpandedNavItem key={item.id} item={item} isActive={active} onClick={onClick} />
                    ) : (
                      <CollapsedNavItem key={item.id} item={item} isActive={active} onClick={onClick} />
                    );
                  })}
                </div>
              </div>
            ))}



            {/* LIBRARY group & Chat History */}
            <div className="mt-auto">
              {/* Ad Copy — Chat History button top of library */}
              {currentRoute === '/adstudio' && activeAdStudioTabId === 'adCopy' && (
                <div className={showExpanded ? 'px-2.5 pb-1' : 'px-2'}>
                  {showExpanded ? (
                    <button
                      type="button"
                      onClick={() => setOpenHistory(!openHistory)}
                      aria-label="Chat History"
                      className={`sidebar-nav-item sidebar-nav-item--expanded ${
                        openHistory ? 'sidebar-nav-item--active' : 'sidebar-nav-item--inactive'
                      } relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5`}
                    >
                      {openHistory && (
                        <span
                          aria-hidden="true"
                          className="nav-accent-bar absolute left-0 top-[12px] bottom-[12px] w-[2.5px] rounded-r-full"
                        />
                      )}
                      <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
                        <History className="sidebar-nav-icon h-[26px] w-[26px] flex-shrink-0" aria-hidden="true" />
                      </div>
                      <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1 text-left">Chat History</span>
                    </button>
                  ) : (
                    <ShadcnTooltip label="Chat History" side="right">
                      <button
                        type="button"
                        onClick={() => setOpenHistory(!openHistory)}
                        aria-label="Chat History"
                        className={`sidebar-nav-item sidebar-nav-item--compact ${
                          openHistory ? 'sidebar-nav-item--active' : 'sidebar-nav-item--inactive'
                        } relative flex w-full flex-col items-center justify-center gap-1.5 rounded-[14px] py-2 h-[76px]`}
                      >
                        {openHistory && (
                          <span
                            aria-hidden="true"
                            className="nav-accent-bar absolute -left-2 top-3.5 bottom-3.5 w-[3px] rounded-r-full dark:left-0 dark:top-2 dark:bottom-2"
                          />
                        )}
                        <div className="flex h-7 w-7 items-center justify-center">
                          <History className="sidebar-nav-icon h-[24px] w-[24px]" aria-hidden="true" />
                        </div>
                        <span className="sidebar-nav-label sidebar-nav-label--compact whitespace-nowrap dark:text-[#AFAFAF]">History</span>
                      </button>
                    </ShadcnTooltip>
                  )}
                </div>
              )}

              {/* Logout (members only) — placed top of the library dividing line */}
              {memberSession && (
                <div className={showExpanded ? 'px-2.5 pb-1' : 'px-2 pb-1'}>
                  {showExpanded ? (
                    <button
                      type="button"
                      onClick={() => {
                        clearWorkspaceToken();
                        window.location.href = '/workspace-login';
                      }}
                      aria-label="Log out"
                      className="sidebar-nav-item sidebar-nav-item--expanded sidebar-nav-item--inactive relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5"
                    >
                      <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
                        <LogOut className="sidebar-nav-icon h-[26px] w-[26px] flex-shrink-0" aria-hidden="true" />
                      </div>
                      <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1 text-left">
                        Log out
                      </span>
                    </button>
                  ) : (
                    <ShadcnTooltip label="Log out" side="right">
                      <button
                        type="button"
                        onClick={() => {
                          clearWorkspaceToken();
                          window.location.href = '/workspace-login';
                        }}
                        aria-label="Log out"
                        className="sidebar-nav-item sidebar-nav-item--compact sidebar-nav-item--inactive relative flex w-full flex-col items-center justify-center gap-1.5 rounded-[14px] py-2 h-[76px]"
                      >
                        <div className="flex h-7 w-7 items-center justify-center">
                          <LogOut className="sidebar-nav-icon h-[24px] w-[24px]" aria-hidden="true" />
                        </div>
                        <span className="sidebar-nav-label sidebar-nav-label--compact whitespace-nowrap dark:text-[#AFAFAF]">
                          Log out
                        </span>
                      </button>
                    </ShadcnTooltip>
                  )}
                </div>
              )}

              {showLibraryGroup && (
                <div>
                  <SectionHeader label="LIBRARY" />
                  <div className={showExpanded ? 'space-y-1 px-2.5' : 'space-y-2 px-2'}>

                    {/* Workspace (owner only) */}
                    {showWorkspace && (() => {
                      const active = currentRoute === '/workspace/members';
                      const doNav = () => {
                        setOpenHistory(false);
                        if (isMobile) setOpenMobile(false);
                      };
                      if (showExpanded) {
                        return (
                          <Link
                            key="workspace"
                            to="/workspace/members"
                            onClick={doNav}
                            aria-current={active ? 'page' : undefined}
                            className={`sidebar-nav-item sidebar-nav-item--expanded${active ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5`}
                          >
                            {active && (
                              <span
                                aria-hidden="true"
                                className="nav-accent-bar absolute left-0 top-[12px] bottom-[12px] w-[2.5px] rounded-r-full"
                              />
                            )}
                            <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
                              <Users className="sidebar-nav-icon h-[26px] w-[26px] flex-shrink-0" />
                            </div>
                            <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1">Workspace</span>
                          </Link>
                        );
                      }
                      return (
                        <ShadcnTooltip key="workspace" label="Workspace" side="right">
                          <Link
                            to="/workspace/members"
                            onClick={doNav}
                            aria-label="Workspace"
                            aria-current={active ? 'page' : undefined}
                            className={`sidebar-nav-item sidebar-nav-item--compact${active ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full flex-col items-center justify-center gap-1.5 rounded-[14px] py-2 h-[76px]`}
                          >
                            {active && (
                              <span
                                aria-hidden="true"
                                className="nav-accent-bar absolute -left-2 top-3.5 bottom-3.5 w-[3px] rounded-r-full dark:left-0 dark:top-2 dark:bottom-2"
                              />
                            )}
                            <div className="flex h-7 w-7 items-center justify-center">
                              <Users className="sidebar-nav-icon h-[24px] w-[24px]" />
                            </div>
                            <span className="sidebar-nav-label sidebar-nav-label--compact whitespace-nowrap dark:text-[#AFAFAF]">
                              Workspace
                            </span>
                          </Link>
                        </ShadcnTooltip>
                      );
                    })()}

                    {/* My Space (gated by canUseMySpace) */}
                    {showMySpace && (() => {
                      const active = currentRoute === '/my-space';
                      const doNav = () => {
                        setOpenHistory(false);
                        dispatch(setActivePage('myVideos'));
                        if (isMobile) setOpenMobile(false);
                      };
                      if (showExpanded) {
                        return (
                          <Link
                            key="myspace"
                            id="sidebar-my-space-button"
                            to="/my-space"
                            onClick={doNav}
                            aria-current={active ? 'page' : undefined}
                            className={`sidebar-nav-item sidebar-nav-item--expanded${active ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5`}
                          >
                            {active && (
                              <span
                                aria-hidden="true"
                                className="nav-accent-bar absolute left-0 top-[12px] bottom-[12px] w-[2.5px] rounded-r-full"
                              />
                            )}
                            <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
                              <Library className="sidebar-nav-icon h-[26px] w-[26px] flex-shrink-0" />
                            </div>
                            <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1 text-left">My Space</span>
                            {savedCount > 0 && renderBadge(savedCount)}
                          </Link>
                        );
                      }
                      return (
                        <ShadcnTooltip key="myspace" label="My Space" side="right">
                          <Link
                            key="myspace"
                            id="sidebar-my-space-button"
                            to="/my-space"
                            onClick={doNav}
                            aria-label="My Space"
                            aria-current={active ? 'page' : undefined}
                            className={`sidebar-nav-item sidebar-nav-item--compact${active ? ' sidebar-nav-item--active' : ' sidebar-nav-item--inactive'} relative flex w-full flex-col items-center justify-center gap-1.5 rounded-[14px] py-2 ${
                              savedCount > 0 ? 'h-[90px]' : 'h-[76px]'
                            }`}
                          >
                            {active && (
                              <span
                                aria-hidden="true"
                                className="nav-accent-bar absolute -left-2 top-3.5 bottom-3.5 w-[3px] rounded-r-full dark:left-0 dark:top-2 dark:bottom-2"
                              />
                            )}
                            <div className="flex h-7 w-7 items-center justify-center">
                              <Library className="sidebar-nav-icon h-[24px] w-[24px]" />
                            </div>
                            <span className="sidebar-nav-label sidebar-nav-label--compact whitespace-nowrap dark:text-[#AFAFAF]">
                              My Space
                            </span>
                            {savedCount > 0 && (
                              <div className="sidebar-nav-badge--compact absolute right-1.5 2xl:right-5 -top-2">
                                {renderBadge(savedCount)}
                              </div>
                            )}
                          </Link>
                        </ShadcnTooltip>
                      );
                    })()}

                  </div>
                </div>
              )}
            </div>

          </nav>
        )}

        {/* Ad Copy — Chat History button (when history drawer is open) */}
        {openHistory && currentRoute === '/adstudio' && activeAdStudioTabId === 'adCopy' && (
          <div className="px-2.5 pb-2 pt-1">
            <button
              type="button"
              onClick={() => setOpenHistory(!openHistory)}
              aria-label="Chat History"
              className="sidebar-nav-item sidebar-nav-item--expanded sidebar-nav-item--inactive relative flex w-full items-center gap-4 rounded-[15px] px-4 py-2.5"
            >
              <div className="flex w-6.5 flex-shrink-0 items-center justify-center">
                <History className="sidebar-nav-icon h-[26px] w-[26px] flex-shrink-0" aria-hidden="true" />
              </div>
              <span className="sidebar-nav-label sidebar-nav-label--expanded flex-1 text-left">Chat History</span>
            </button>
          </div>
        )}

        {/* Divider above profile */}
        {(!memberSession || (memberSession && canUseWorkspaceFeature('profile', workspacePayload))) && (
          <div
            className={
              showExpanded || openHistory
                ? 'sidebar-divider mx-3.5 flex-shrink-0 border-t dark:border-white/15'
                : 'sidebar-section-divider mx-auto mb-1.5 h-px w-9 flex-shrink-0 dark:bg-white/15'
            }
          />
        )}

        {/* ── PROFILE FOOTER (anchored at bottom) ───────────────────────────── */}
        {(!memberSession || (memberSession && canUseWorkspaceFeature('profile', workspacePayload))) ? (
          <div
            className={`relative flex flex-shrink-0 items-center justify-center ${
              openHistory ? 'h-[76px] px-2.5' : 'h-[64px] 2xl:h-[72px] pb-2 pt-1'
            }`}
          >
            {currentRoute === '/profile' && !openHistory && (
              <span
                aria-hidden="true"
                className="nav-accent-bar absolute left-0 top-1/2 -translate-y-1/2 h-7 w-[3px] rounded-r-full"
              />
            )}
            <ShadcnTooltip label={openHistory ? undefined : 'User Profile'} side="right">
              <Link
                to="/profile"
                onClick={() => {
                  setOpenHistory(false);
                  if (isMobile) setOpenMobile(false);
                }}
                aria-label={openHistory ? undefined : 'User Profile'}
                aria-current={currentRoute === '/profile' ? 'page' : undefined}
                className={
                  openHistory
                    ? `sidebar-nav-item sidebar-nav-item--expanded${
                        currentRoute === '/profile'
                          ? ' sidebar-nav-item--active'
                          : ' sidebar-nav-item--inactive'
                      } relative flex w-full items-center gap-3 rounded-[15px] px-3 py-2 transition-all`
                    : 'group relative flex items-center justify-center rounded-full focus:outline-none cursor-pointer'
                }
              >
                {currentRoute === '/profile' && openHistory && (
                  <span
                    aria-hidden="true"
                    className="nav-accent-bar absolute left-0 top-[11px] bottom-[11px] w-[2px] rounded-r-full"
                  />
                )}
                {/* Avatar */}
                <div
                  className={`sidebar-profile-button ${
                    currentRoute === '/profile' ? 'sidebar-profile-button-active' : ''
                  } relative flex h-10 w-10 2xl:h-11 2xl:w-11 flex-shrink-0 items-center justify-center overflow-hidden rounded-full shadow-xs transition-transform duration-200 group-hover:scale-105 active:scale-95`}
                >
                  {profileImage ? (
                    <img
                      src={profileImage}
                      alt=""
                      aria-hidden="true"
                      className="sidebar-profile-avatar h-full w-full rounded-full object-cover"
                    />
                  ) : (
                    <span className="sidebar-profile-avatar flex h-full w-full items-center justify-center text-center text-xs 2xl:text-[13px] font-bold">
                      {profileInitials}
                    </span>
                  )}
                </div>

                {/* Name + role */}
                {openHistory && (
                  <div className="flex min-w-0 flex-1 flex-col justify-center">
                    <span
                      className="sidebar-profile-name truncate dark:text-white"
                      title={profileDisplayName}
                    >
                      {profileDisplayName}
                    </span>
                    <span className="sidebar-profile-role dark:text-[#5A5A5A]">
                      {memberSession ? 'Member' : 'Owner'}
                    </span>
                  </div>
                )}
              </Link>
            </ShadcnTooltip>
          </div>
        ) : null}

        <div className="sidebar-edge-divider absolute top-0 right-0 h-full w-[1px]" />
      </div>
    </Sidebar>
  );
};

export default AppSidebar;
