#!/usr/bin/env node
/**
 * Phase 9 — rotationService pure-helper tests + arg-validation contracts.
 *
 * No SDK, no Mongo. Run: node test/autopilot/phase9-rotation.test.js
 */

const assert = require("node:assert/strict");

const {
  rotateForAccount,
  isRotationFinding,
  pickRotationDraft,
  countRecentRotations,
} = require("../../services/autopilot/rotationService");

let pass = 0;
let fail = 0;
const FAILURES = [];
const PENDING = [];

function test(name, fn) {
  try {
    fn();
    pass += 1;
    console.log(`  ✓ ${name}`);
  } catch (err) {
    fail += 1;
    FAILURES.push({ name, err });
    console.log(`  ✗ ${name}`);
    console.log(`      ${err.message}`);
  }
}

// Queues an async test; group() awaits all queued tests before returning so
// the summary at the bottom sees accurate pass/fail counts.
function asyncTest(name, fn) {
  PENDING.push(
    (async () => {
      try {
        await fn();
        pass += 1;
        console.log(`  ✓ ${name}`);
      } catch (err) {
        fail += 1;
        FAILURES.push({ name, err });
        console.log(`  ✗ ${name}`);
        console.log(`      ${err.message}`);
      }
    })(),
  );
}

async function group(label, fn) {
  console.log(`\n${label}`);
  fn();
  if (PENDING.length) {
    const inflight = PENDING.splice(0);
    await Promise.all(inflight);
  }
}

// ---------------------------------------------------------------------------

async function main() {

await group("isRotationFinding", () => {
  test("AUD-36 ad-level finding with adset_id is a rotation finding", () => {
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-36",
        entity_type: "ad",
        data: { adset_id: "as1" },
      }),
      true,
    );
  });
  test("AUD-12 (adset frequency) is NOT a rotation finding (v1)", () => {
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-12",
        entity_type: "adset",
        data: { adset_id: "as1" },
      }),
      false,
    );
  });
  test("AUD-36 on adset (not ad) is NOT a rotation finding", () => {
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-36",
        entity_type: "adset",
        data: { adset_id: "as1" },
      }),
      false,
    );
  });
  test("AUD-36 ad finding without data.adset_id is NOT a rotation finding", () => {
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-36",
        entity_type: "ad",
        data: {},
      }),
      false,
    );
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-36",
        entity_type: "ad",
      }),
      false,
    );
  });
  test("Other rule ids (AUD-01, AUD-32) are NOT rotation findings", () => {
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-01",
        entity_type: "ad",
        data: { adset_id: "as1" },
      }),
      false,
    );
    assert.equal(
      isRotationFinding({
        rule_id: "AUD-32",
        entity_type: "campaign",
      }),
      false,
    );
  });
  test("null / undefined finding returns false", () => {
    assert.equal(isRotationFinding(null), false);
    assert.equal(isRotationFinding(undefined), false);
  });
});

await group("pickRotationDraft — preference + filtering", () => {
  const draft = (over = {}) => ({
    creativeId: "cr1",
    name: "draft",
    rotationReady: true,
    autoGenerated: false,
    usedByAutopilotAt: null,
    usedByEntityId: null,
    rotationGroupId: null,
    adsetId: null,
    createdAt: new Date("2026-01-01"),
    ...over,
    // _id last so it isn't overwritten by spread; namespaces test ids so a
    // bare "1" doesn't collide with anything else.
    _id: "d" + (over._id || "x"),
  });

  test("returns null on empty / non-array input", () => {
    assert.equal(pickRotationDraft([], "as1"), null);
    assert.equal(pickRotationDraft(null, "as1"), null);
    assert.equal(pickRotationDraft(undefined, "as1"), null);
  });

  test("returns null when no draft is rotationReady", () => {
    const d = draft({ rotationReady: false });
    assert.equal(pickRotationDraft([d], "as1"), null);
  });

  test("returns null when all drafts are already used", () => {
    const d = draft({ usedByAutopilotAt: new Date() });
    assert.equal(pickRotationDraft([d], "as1"), null);
  });

  test("prefers a draft pinned to the same adsetId over a generic one", () => {
    const generic = draft({ _id: "1", adsetId: null });
    const pinned = draft({ _id: "2", adsetId: "as1" });
    assert.equal(pickRotationDraft([generic, pinned], "as1")._id, "d2");
  });

  test("falls back to generic when no pinned draft exists for the adset", () => {
    const generic = draft({ _id: "1", adsetId: null });
    const otherPinned = draft({ _id: "2", adsetId: "as_other" });
    const out = pickRotationDraft([generic, otherPinned], "as1");
    assert.equal(out._id, "d1");
  });

  test("returns null when only drafts pinned to OTHER adsets exist", () => {
    const otherPinned = draft({ _id: "1", adsetId: "as_other" });
    assert.equal(pickRotationDraft([otherPinned], "as1"), null);
  });

  test("FIFO: oldest createdAt wins among eligible drafts", () => {
    const newer = draft({
      _id: "1",
      adsetId: null,
      createdAt: new Date("2026-04-01"),
    });
    const older = draft({
      _id: "2",
      adsetId: null,
      createdAt: new Date("2026-01-01"),
    });
    assert.equal(pickRotationDraft([newer, older], "as1")._id, "d2");
  });

  test("ignores drafts missing the rotationReady flag entirely", () => {
    const d = draft();
    delete d.rotationReady;
    assert.equal(pickRotationDraft([d], "as1"), null);
  });
});

await group("countRecentRotations — per-adset 30d cap", () => {
  const now = Date.now();
  const days = (n) => new Date(now - n * 24 * 60 * 60 * 1000);

  test("returns 0 for empty / non-array", () => {
    assert.equal(countRecentRotations([], "as1"), 0);
    assert.equal(countRecentRotations(null, "as1"), 0);
    assert.equal(countRecentRotations(undefined, "as1"), 0);
  });

  test("counts rows for the given adsetId within window", () => {
    const rows = [
      { adsetId: "as1", runAt: days(1) },
      { adsetId: "as1", runAt: days(20) },
      { adsetId: "as1", runAt: days(40) }, // outside 30d
      { adsetId: "as_other", runAt: days(1) }, // wrong adset
    ];
    assert.equal(countRecentRotations(rows, "as1"), 2);
  });

  test("custom days parameter narrows the window", () => {
    const rows = [
      { adsetId: "as1", runAt: days(1) },
      { adsetId: "as1", runAt: days(10) },
      { adsetId: "as1", runAt: days(20) },
    ];
    assert.equal(countRecentRotations(rows, "as1", 7), 1);
    assert.equal(countRecentRotations(rows, "as1", 30), 3);
  });

  test("rows missing runAt are skipped", () => {
    const rows = [
      { adsetId: "as1", runAt: days(1) },
      { adsetId: "as1" }, // no runAt
      null,
    ];
    assert.equal(countRecentRotations(rows, "as1"), 1);
  });
});

await group("rotateForAccount — entry-point validation", () => {
  asyncTest("rejects when neither accessToken nor audit is provided", async () => {
    await assert.rejects(
      rotateForAccount({ userId: "u", adAccountId: "act_1" }),
      /accessToken is required when no pre-fetched audit/,
    );
  });

  asyncTest("rejects when userId is missing", async () => {
    await assert.rejects(
      rotateForAccount({ adAccountId: "act_1", accessToken: "t" }),
      /userId is required/,
    );
  });

  asyncTest("rejects when adAccountId is missing", async () => {
    await assert.rejects(
      rotateForAccount({ userId: "u", accessToken: "t" }),
      /adAccountId is required/,
    );
  });

  asyncTest(
    "with audit provided (no fatigue findings) returns a valid summary without Meta calls",
    async () => {
      // Audit with empty findings → no fatigue, no rotation, no Mongo writes.
      // Validates the early-return path doesn't try to hit the SDK.
      const result = await rotateForAccount({
        userId: "u",
        adAccountId: "act_1",
        audit: { findings: [], account_name: "Test" },
        dryRun: true,
      });
      assert.equal(result.findings_count, 0);
      assert.equal(result.evaluated, 0);
      assert.equal(result.rotated, 0);
      assert.equal(result.would_rotate, 0);
      assert.equal(result.skipped, 0);
      assert.equal(result.failed, 0);
      assert.equal(result.dryRun, true);
      assert.equal(result.adAccountId, "act_1");
    },
  );
});

} // end main()

// ---------------------------------------------------------------------------

main().then(() => {
  console.log(`\n${pass} passed, ${fail} failed`);
  if (fail > 0) {
    console.log("\nFailures:");
    for (const { name, err } of FAILURES) {
      console.log(`  - ${name}: ${err.stack || err.message}`);
    }
    process.exit(1);
  }
});
