const crypto = require("node:crypto");
const jwt = require("jsonwebtoken");
const mongoose = require("mongoose");
const Workspace = require("../../Module/workspace/workspace");
const WorkspaceMemberAccount = require(
  "../../Module/workspace/workspaceMemberAccount",
);
const WorkspaceMemberLoginToken = require(
  "../../Module/workspace/workspaceMemberLoginToken",
);
const WorkspaceMembership = require("../../Module/workspace/workspaceMembership");
const UserProfile = require("../../Module/user/userProfileModel");
const { requireSponsor } = require("./workspaceSponsor");
const { sendLoginLink } = require("./workspaceEmail");
const {
  acceptInvitation,
  accountIdFromActor,
  actorId,
  memberName,
  tokenHash,
} = require("./workspaceService");
const {
  normalizeEmail,
  normalizeFeatures,
  workspaceError,
} = require("./workspaceConfig");

function ownerClaims(owner) {
  const rawId =
    owner.amember_user_id || String(owner.user_id || "").replace(/^GPT-/, "");
  const numericId = Number(rawId);
  return {
    status: true,
    user_id:
      Number.isSafeInteger(numericId) && numericId > 0 ? numericId : rawId,
    login: owner.login,
    user_name:
      owner.name ||
      [owner.name_f, owner.name_l].filter(Boolean).join(" ").trim(),
    user_email: owner.email,
    name_f: owner.name_f || "",
    name_l: owner.name_l || "",
    userSubscriptionType: owner.subscriptions || {},
    created_from: owner.created_from || "GPT",
    autoGenerated: false,
  };
}

function isSponsorEligibilityError(error) {
  return [
    "WORKSPACE_SPONSOR_PLAN_REQUIRED",
    "WORKSPACE_SPONSOR_INELIGIBLE",
  ].includes(error?.code);
}

function sameFeatures(left, right) {
  return JSON.stringify(normalizeFeatures(left)) ===
    JSON.stringify(normalizeFeatures(right));
}

function createWorkspaceMemberAuth(overrides = {}) {
  const deps = {
    Workspace,
    WorkspaceMemberAccount,
    WorkspaceMemberLoginToken,
    WorkspaceMembership,
    UserProfile,
    acceptInvitation,
    requireSponsor,
    sendLoginLink,
    jwtSecret: process.env.JWT_SECRET_KEY,
    tokenMinutes: Number(process.env.WORKSPACE_MEMBER_TOKEN_MINUTES) || 60,
    loginTtlMs: Number(process.env.WORKSPACE_MEMBER_LOGIN_TOKEN_TTL_MS) ||
      15 * 60 * 1000,
    exposeLinks:
      process.env.NODE_ENV !== "production" &&
      process.env.WORKSPACE_EXPOSE_LOGIN_LINK === "true",
    now: () => new Date(),
    randomToken: () => crypto.randomBytes(32).toString("base64url"),
    ...overrides,
  };

  function requireConfiguration() {
    if (!deps.jwtSecret) {
      throw workspaceError(
        "WORKSPACE_AUTH_NOT_CONFIGURED",
        "Workspace authentication is not configured",
        503,
      );
    }
  }

  async function activeChoices(memberAccountId, workspaceId) {
    // Reject a malformed id before it reaches Mongoose, which would otherwise
    // raise a CastError that surfaces as an opaque 500.
    if (workspaceId && !mongoose.isValidObjectId(workspaceId)) {
      throw workspaceError("WORKSPACE_NOT_FOUND", "Workspace not found", 404);
    }
    const filter = {
      memberAccountId,
      status: "active",
    };
    if (workspaceId) filter.workspaceId = workspaceId;
    const memberships = await deps.WorkspaceMembership.find(filter).lean();
    if (!memberships.length) {
      throw workspaceError(
        "WORKSPACE_MEMBERSHIP_REQUIRED",
        "This account does not have active workspace access",
        403,
      );
    }
    const workspaces = await deps.Workspace.find({
      _id: { $in: memberships.map((entry) => entry.workspaceId) },
      status: "active",
    }).lean();
    const byId = new Map(
      workspaces.map((workspace) => [String(workspace._id), workspace]),
    );
    return memberships
      .map((membership) => ({
        membership,
        workspace: byId.get(String(membership.workspaceId)),
      }))
      .filter((entry) => entry.workspace)
      .sort(
        (left, right) =>
          String(left.workspace.name).localeCompare(String(right.workspace.name)) ||
          String(left.workspace._id).localeCompare(String(right.workspace._id)),
      );
  }

  async function loadOwner(workspace) {
    const sponsor = await deps.requireSponsor(workspace.ownerUserId);
    return sponsor.profile;
  }

  function issueToken({ account, membership, workspace, owner }) {
    requireConfiguration();
    return jwt.sign(
      {
        ...ownerClaims(owner),
        actorUserId: actorId(account),
        actorUserEmail: account.email,
        actorUserName: memberName(account),
        actorAccountType: "workspace_member",
        workspace_id: String(workspace._id),
        workspace_name: workspace.name,
        workspace_features: normalizeFeatures(membership.features),
        session_scope: "workspace_member",
        delegated: true,
      },
      deps.jwtSecret,
      {
        algorithm: "HS512",
        expiresIn: `${Math.max(1, deps.tokenMinutes)}m`,
      },
    );
  }

  async function sessionFor({ account, workspaceId }) {
    const choices = await activeChoices(account._id, workspaceId);
    let lastSponsorError;
    for (const selected of choices) {
      try {
        const owner = await loadOwner(selected.workspace);
        return {
          token: issueToken({
            account,
            membership: selected.membership,
            workspace: selected.workspace,
            owner,
          }),
          workspaceId: String(selected.workspace._id),
          workspaceName: selected.workspace.name,
          features: normalizeFeatures(selected.membership.features),
          actorUserId: actorId(account),
        };
      } catch (error) {
        if (workspaceId || !isSponsorEligibilityError(error)) throw error;
        lastSponsorError = error;
      }
    }
    if (lastSponsorError) {
      throw workspaceError(
        "WORKSPACE_SPONSOR_INELIGIBLE",
        "No workspace with an active sponsor is available",
        403,
      );
    }
    throw workspaceError("WORKSPACE_NOT_FOUND", "Workspace not found", 404);
  }

  async function accept({ token, firstName, lastName }) {
    requireConfiguration();
    const accepted = await deps.acceptInvitation({
      rawToken: token,
      firstName,
      lastName,
    });
    return sessionFor({
      account: accepted.account,
      workspaceId: accepted.workspace._id,
    });
  }

  async function requestLogin(email) {
    const normalizedEmail = normalizeEmail(email);
    if (!normalizedEmail) return { sent: true };
    const account = await deps.WorkspaceMemberAccount.findOne({
      email: normalizedEmail,
      status: "active",
    }).lean();
    if (!account) return { sent: true };

    const membership = await deps.WorkspaceMembership.findOne({
      memberAccountId: account._id,
      status: "active",
    }).lean();
    if (!membership) return { sent: true };

    const rawToken = deps.randomToken();
    await deps.WorkspaceMemberLoginToken.create({
      memberAccountId: account._id,
      tokenHash: tokenHash(rawToken),
      expiresAt: new Date(deps.now().getTime() + deps.loginTtlMs),
    });
    const delivery = await deps.sendLoginLink({
      to: account.email,
      token: rawToken,
    });
    const result = { sent: true };
    if (deps.exposeLinks && !delivery.sent) result.token = rawToken;
    return result;
  }

  async function consumeLogin(token) {
    requireConfiguration();
    const now = deps.now();
    const hash = tokenHash(token);
    const loginToken = await deps.WorkspaceMemberLoginToken.findOne({
      tokenHash: hash,
      usedAt: null,
      expiresAt: { $gt: now },
    }).lean();
    if (!loginToken) {
      throw workspaceError(
        "WORKSPACE_LOGIN_LINK_INVALID",
        "This sign-in link is invalid or expired",
        410,
      );
    }
    const account = await deps.WorkspaceMemberAccount.findOne({
      _id: loginToken.memberAccountId,
      status: "active",
    }).lean();
    if (!account) {
      throw workspaceError(
        "WORKSPACE_MEMBER_DISABLED",
        "This workspace member account is unavailable",
        403,
      );
    }

    const session = await sessionFor({ account });
    const consumed = await deps.WorkspaceMemberLoginToken.findOneAndUpdate(
      {
        _id: loginToken._id,
        usedAt: null,
        expiresAt: { $gt: now },
      },
      { $set: { usedAt: now } },
      { new: true },
    );
    if (!consumed) {
      throw workspaceError(
        "WORKSPACE_LOGIN_LINK_USED",
        "This sign-in link has already been used",
        410,
      );
    }
    await deps.WorkspaceMemberAccount.updateOne(
      { _id: account._id },
      { $set: { lastLoginAt: now } },
    );
    return session;
  }

  async function switchWorkspace({ actorUserId, workspaceId }) {
    const memberAccountId = accountIdFromActor(actorUserId);
    if (!memberAccountId) {
      throw workspaceError(
        "WORKSPACE_MEMBER_SESSION_REQUIRED",
        "Workspace member sign-in is required",
        403,
      );
    }
    const account = await deps.WorkspaceMemberAccount.findOne({
      _id: memberAccountId,
      status: "active",
    }).lean();
    if (!account) {
      throw workspaceError(
        "WORKSPACE_MEMBER_DISABLED",
        "This workspace member account is unavailable",
        403,
      );
    }
    return sessionFor({ account, workspaceId });
  }

  async function listMemberWorkspaces(actorUserId) {
    const memberAccountId = accountIdFromActor(actorUserId);
    if (!memberAccountId) return [];
    const choices = await activeChoices(memberAccountId);
    const eligible = [];
    for (const choice of choices) {
      try {
        await loadOwner(choice.workspace);
        eligible.push(choice);
      } catch (error) {
        if (!isSponsorEligibilityError(error)) throw error;
        // An expired owner must not prevent access to another valid workspace.
      }
    }
    return eligible.map(({ workspace, membership }) => ({
      id: String(workspace._id),
      name: workspace.name,
      ownerUserId: workspace.ownerUserId,
      features: normalizeFeatures(membership.features),
    }));
  }

  async function validateSession(user) {
    if (user?.session_scope !== "workspace_member" || user?.delegated !== true) {
      return null;
    }
    const memberAccountId = accountIdFromActor(user.actorUserId);
    if (!memberAccountId) {
      throw workspaceError(
        "WORKSPACE_SESSION_INVALID",
        "Workspace session is invalid",
        403,
      );
    }
    const account = await deps.WorkspaceMemberAccount.findOne({
      _id: memberAccountId,
      status: "active",
    }).lean();
    if (!account) {
      throw workspaceError(
        "WORKSPACE_MEMBER_DISABLED",
        "Workspace access was removed",
        403,
      );
    }
    const choices = await activeChoices(memberAccountId, user.workspace_id);
    const selected = choices[0];
    // activeChoices only throws when the member has no active membership at
    // all. An active membership whose workspace has since been archived leaves
    // an empty list, which would otherwise dereference undefined here.
    if (!selected) {
      throw workspaceError(
        "WORKSPACE_MEMBERSHIP_REQUIRED",
        "Workspace access was removed",
        403,
      );
    }
    const owner = await loadOwner(selected.workspace);
    const latestFeatures = normalizeFeatures(selected.membership.features);
    const claimsAreStale =
      !sameFeatures(user.workspace_features, latestFeatures) ||
      user.workspace_name !== selected.workspace.name;
    user.workspace_features = latestFeatures;
    user.workspace_name = selected.workspace.name;
    return {
      account,
      ...selected,
      refreshedToken: claimsAreStale
        ? issueToken({
            account,
            membership: selected.membership,
            workspace: selected.workspace,
            owner,
          })
        : null,
    };
  }

  return {
    accept,
    consumeLogin,
    listMemberWorkspaces,
    requestLogin,
    switchWorkspace,
    validateSession,
  };
}

const service = createWorkspaceMemberAuth();

module.exports = {
  ...service,
  createWorkspaceMemberAuth,
  ownerClaims,
};
