const jwt = require("jsonwebtoken");
const mongoose = require("mongoose");
const Workspace = require("../../Module/workspace/workspace");
const WorkspaceMemberAccount = require(
  "../../Module/workspace/workspaceMemberAccount",
);
const WorkspaceMembership = require("../../Module/workspace/workspaceMembership");
const UserProfile = require("../../Module/user/userProfileModel");
const { requireSponsor } = require("./workspaceSponsor");
const { hashClientSecret, verifyClientSecret } = require(
  "../oauth/clientSecretService",
);
const {
  acceptInvitation,
  accountIdFromActor,
  actorId,
  memberName,
} = require("./workspaceService");
const {
  normalizeEmail,
  normalizeFeatures,
  workspaceError,
} = require("./workspaceConfig");

// A fixed dummy hash so an unknown-email or no-password-yet lookup still
// pays the same scrypt cost a real verification would — otherwise response
// timing would leak which case occurred, defeating the point of collapsing
// them into one generic error below.
const DUMMY_PASSWORD_HASH = hashClientSecret(
  "workspace-member-login-dummy-hash-do-not-use",
);

function ownerClaims(owner) {
  const rawId =
    owner.amember_user_id || String(owner.user_id || "").replace(/^GPT-/, "");
  const numericId = Number(rawId);
  return {
    status: true,
    user_id:
      Number.isSafeInteger(numericId) && numericId > 0 ? numericId : rawId,
    login: owner.login,
    user_name:
      owner.name ||
      [owner.name_f, owner.name_l].filter(Boolean).join(" ").trim(),
    user_email: owner.email,
    name_f: owner.name_f || "",
    name_l: owner.name_l || "",
    userSubscriptionType: owner.subscriptions || {},
    created_from: owner.created_from || "GPT",
    autoGenerated: false,
  };
}

function isSponsorEligibilityError(error) {
  return [
    "WORKSPACE_SPONSOR_PLAN_REQUIRED",
    "WORKSPACE_SPONSOR_INELIGIBLE",
  ].includes(error?.code);
}

function sameFeatures(left, right) {
  return JSON.stringify(normalizeFeatures(left)) ===
    JSON.stringify(normalizeFeatures(right));
}

function createWorkspaceMemberAuth(overrides = {}) {
  const deps = {
    Workspace,
    WorkspaceMemberAccount,
    WorkspaceMembership,
    UserProfile,
    acceptInvitation,
    requireSponsor,
    verifyClientSecret,
    jwtSecret: process.env.JWT_SECRET_KEY,
    tokenMinutes: Number(process.env.WORKSPACE_MEMBER_TOKEN_MINUTES) || 60,
    now: () => new Date(),
    ...overrides,
  };

  function requireConfiguration() {
    if (!deps.jwtSecret) {
      throw workspaceError(
        "WORKSPACE_AUTH_NOT_CONFIGURED",
        "Workspace authentication is not configured",
        503,
      );
    }
  }

  async function activeChoices(memberAccountId, workspaceId) {
    // Reject a malformed id before it reaches Mongoose, which would otherwise
    // raise a CastError that surfaces as an opaque 500.
    if (workspaceId && !mongoose.isValidObjectId(workspaceId)) {
      throw workspaceError("WORKSPACE_NOT_FOUND", "Workspace not found", 404);
    }
    const filter = {
      memberAccountId,
      status: "active",
    };
    if (workspaceId) filter.workspaceId = workspaceId;
    const memberships = await deps.WorkspaceMembership.find(filter).lean();
    if (!memberships.length) {
      throw workspaceError(
        "WORKSPACE_MEMBERSHIP_REQUIRED",
        "This account does not have active workspace access",
        403,
      );
    }
    const workspaces = await deps.Workspace.find({
      _id: { $in: memberships.map((entry) => entry.workspaceId) },
      status: "active",
    }).lean();
    const byId = new Map(
      workspaces.map((workspace) => [String(workspace._id), workspace]),
    );
    return memberships
      .map((membership) => ({
        membership,
        workspace: byId.get(String(membership.workspaceId)),
      }))
      .filter((entry) => entry.workspace)
      .sort(
        (left, right) =>
          String(left.workspace.name).localeCompare(String(right.workspace.name)) ||
          String(left.workspace._id).localeCompare(String(right.workspace._id)),
      );
  }

  async function loadOwner(workspace) {
    const sponsor = await deps.requireSponsor(workspace.ownerUserId);
    return sponsor.profile;
  }

  function issueToken({ account, membership, workspace, owner }) {
    requireConfiguration();
    return jwt.sign(
      {
        ...ownerClaims(owner),
        actorUserId: actorId(account),
        actorUserEmail: account.email,
        actorUserName: memberName(account),
        actorAccountType: "workspace_member",
        workspace_id: String(workspace._id),
        workspace_name: workspace.name,
        workspace_features: normalizeFeatures(membership.features),
        session_scope: "workspace_member",
        delegated: true,
      },
      deps.jwtSecret,
      {
        algorithm: "HS512",
        expiresIn: `${Math.max(1, deps.tokenMinutes)}m`,
      },
    );
  }

  async function sessionFor({ account, workspaceId }) {
    const choices = await activeChoices(account._id, workspaceId);
    let lastSponsorError;
    for (const selected of choices) {
      try {
        const owner = await loadOwner(selected.workspace);
        return {
          token: issueToken({
            account,
            membership: selected.membership,
            workspace: selected.workspace,
            owner,
          }),
          workspaceId: String(selected.workspace._id),
          workspaceName: selected.workspace.name,
          features: normalizeFeatures(selected.membership.features),
          actorUserId: actorId(account),
        };
      } catch (error) {
        if (workspaceId || !isSponsorEligibilityError(error)) throw error;
        lastSponsorError = error;
      }
    }
    if (lastSponsorError) {
      throw workspaceError(
        "WORKSPACE_SPONSOR_INELIGIBLE",
        "No workspace with an active sponsor is available",
        403,
      );
    }
    throw workspaceError("WORKSPACE_NOT_FOUND", "Workspace not found", 404);
  }

  async function accept({ token, firstName, lastName, password }) {
    requireConfiguration();
    const accepted = await deps.acceptInvitation({
      rawToken: token,
      firstName,
      lastName,
      password,
    });
    return sessionFor({
      account: accepted.account,
      workspaceId: accepted.workspace._id,
    });
  }

  async function login({ email, password }) {
    requireConfiguration();
    const genericError = () =>
      workspaceError(
        "WORKSPACE_INVALID_CREDENTIALS",
        "Incorrect email or password",
        401,
      );
    const normalizedEmail = normalizeEmail(email);
    if (!normalizedEmail || !password) throw genericError();

    const account = await deps.WorkspaceMemberAccount.findOne({
      email: normalizedEmail,
      status: "active",
    }).lean();

    // Always verify against something, even when the account/password
    // doesn't exist, so failure timing can't be used to probe which emails
    // are registered — see DUMMY_PASSWORD_HASH above.
    const storedHash = account?.passwordHash || DUMMY_PASSWORD_HASH;
    const passwordMatches = deps.verifyClientSecret(String(password), storedHash);
    if (!account || !account.passwordHash || !passwordMatches) {
      throw genericError();
    }

    const session = await sessionFor({ account });
    await deps.WorkspaceMemberAccount.updateOne(
      { _id: account._id },
      { $set: { lastLoginAt: deps.now() } },
    );
    return session;
  }

  async function switchWorkspace({ actorUserId, workspaceId }) {
    const memberAccountId = accountIdFromActor(actorUserId);
    if (!memberAccountId) {
      throw workspaceError(
        "WORKSPACE_MEMBER_SESSION_REQUIRED",
        "Workspace member sign-in is required",
        403,
      );
    }
    const account = await deps.WorkspaceMemberAccount.findOne({
      _id: memberAccountId,
      status: "active",
    }).lean();
    if (!account) {
      throw workspaceError(
        "WORKSPACE_MEMBER_DISABLED",
        "This workspace member account is unavailable",
        403,
      );
    }
    return sessionFor({ account, workspaceId });
  }

  async function listMemberWorkspaces(actorUserId) {
    const memberAccountId = accountIdFromActor(actorUserId);
    if (!memberAccountId) return [];
    const choices = await activeChoices(memberAccountId);
    const eligible = [];
    for (const choice of choices) {
      try {
        await loadOwner(choice.workspace);
        eligible.push(choice);
      } catch (error) {
        if (!isSponsorEligibilityError(error)) throw error;
        // An expired owner must not prevent access to another valid workspace.
      }
    }
    return eligible.map(({ workspace, membership }) => ({
      id: String(workspace._id),
      name: workspace.name,
      ownerUserId: workspace.ownerUserId,
      features: normalizeFeatures(membership.features),
    }));
  }

  async function validateSession(user) {
    if (user?.session_scope !== "workspace_member" || user?.delegated !== true) {
      return null;
    }
    const memberAccountId = accountIdFromActor(user.actorUserId);
    if (!memberAccountId) {
      throw workspaceError(
        "WORKSPACE_SESSION_INVALID",
        "Workspace session is invalid",
        403,
      );
    }
    const account = await deps.WorkspaceMemberAccount.findOne({
      _id: memberAccountId,
      status: "active",
    }).lean();
    if (!account) {
      throw workspaceError(
        "WORKSPACE_MEMBER_DISABLED",
        "Workspace access was removed",
        403,
      );
    }
    const choices = await activeChoices(memberAccountId, user.workspace_id);
    const selected = choices[0];
    // activeChoices only throws when the member has no active membership at
    // all. An active membership whose workspace has since been archived leaves
    // an empty list, which would otherwise dereference undefined here.
    if (!selected) {
      throw workspaceError(
        "WORKSPACE_MEMBERSHIP_REQUIRED",
        "Workspace access was removed",
        403,
      );
    }
    // Confirms the owner's subscription is still eligible to sponsor this
    // member on every request — not just something issueToken needed.
    await loadOwner(selected.workspace);
    const latestFeatures = normalizeFeatures(selected.membership.features);
    const claimsAreStale =
      !sameFeatures(user.workspace_features, latestFeatures) ||
      user.workspace_name !== selected.workspace.name;
    if (claimsAreStale) {
      // Force a clean re-login instead of silently reissuing a token and
      // trusting every request path (fetch, axios, concurrent in-flight
      // requests on the client) to apply it exactly once. This reuses the
      // already-guarded 403 -> logout flow instead of a bespoke silent-
      // refresh mechanism.
      throw workspaceError(
        "WORKSPACE_ACCESS_CHANGED",
        "Your workspace access changed. Sign in again to continue.",
        403,
      );
    }
    return { account, ...selected };
  }

  return {
    accept,
    listMemberWorkspaces,
    login,
    switchWorkspace,
    validateSession,
  };
}

const service = createWorkspaceMemberAuth();

module.exports = {
  ...service,
  createWorkspaceMemberAuth,
  ownerClaims,
};
