const mongoose = require("mongoose");

/**
 * adRotationDraft — Phase 9 rotation queue.
 *
 * One document per draftable ad creative the user (or Phase 10 auto-gen) has
 * marked as "ready to be swapped in when an ad fatigues." The rotation service
 * (`services/autopilot/rotationService.js`) reads this collection when AUD-36
 * fires, picks an unused matching draft, and creates a new Meta Ad referencing
 * `creativeId` on the fatigued ad's parent adset (or `adsetId` here if pre-
 * targeted). The draft is single-use: `usedByAutopilotAt` is stamped so we
 * never post the same creative twice in rotation.
 *
 * Shape per PRD §8.2 — `Draft` model extension fields are inlined here as a
 * dedicated collection rather than bolted onto the existing chat-session
 * `Draft.js` (which the codebase audit revealed is unrelated to ad drafts).
 *
 * Population path (out of scope for Phase 9 v1): a future "Save as rotation
 * draft" UI in /adstudio writes here. Phase 10 auto-generation also writes
 * here with `autoGenerated: true, rotationReady: false` until human review.
 */
const adRotationDraftSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true, index: true },
    adAccountId: { type: String, required: true, index: true },

    // Optional — when set, draft is pinned to one adset; rotation will only
    // consider it for fatigue findings on that adset. When null, draft is a
    // generic candidate available to any fatigued ad in the account.
    adsetId: { type: String, default: null, index: true },

    // Pre-built Meta creative the rotation will reference. Required: the
    // rotation flow doesn't build creatives, it only links existing ones to
    // a new Ad object.
    creativeId: { type: String, required: true },

    // Proposed name for the new ad. Rotation may suffix with " (rotation)" or
    // similar — service decides the final name.
    name: { type: String, required: true },

    // True when the user (or Phase 10 review flow) has approved this draft
    // for live rotation. False on auto-generated drafts awaiting human OK.
    rotationReady: { type: Boolean, default: false, index: true },

    // True when produced by Phase 10's auto-generation path. Lets the UI
    // separate "user-saved" from "machine-suggested" entries in the queue.
    autoGenerated: { type: Boolean, default: false },

    // Idempotency: stamped the first time rotation picks this draft. After
    // this, the queue picker filters it out so the same creative is never
    // posted twice in rotation.
    usedByAutopilotAt: { type: Date, default: null, index: true },

    // Which fatigued ad id this draft replaced — useful for "what swapped
    // in for AdX?" debugging.
    usedByEntityId: { type: String, default: null },

    // Pairs the create-action and pause-action rows in autopilotActionLog so
    // the UI can show "rotation event: paused old → posted new" as a unit.
    rotationGroupId: { type: String, default: null, index: true },
  },
  { timestamps: true },
);

// Common queries: find all unused, rotation-ready drafts in an account, then
// prefer ones pinned to the same adset as the fatigued ad. Compound index
// matches that flow.
adRotationDraftSchema.index({
  adAccountId: 1,
  rotationReady: 1,
  usedByAutopilotAt: 1,
});

module.exports = mongoose.model("AdRotationDraft", adRotationDraftSchema);
